spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_caso_autoservicio
    username: root
    password: Joel2009
    driver-class-name: com.mysql.cj.jdbc.Driver
